import { Container, Content } from "../About/styles";
export default function Curiosity() {
  return (
    <Container>
      <Content>
        <h1>Elden Ring: 5 conselhos que vale a pena seguir no começo do jogo</h1>
        <p>Ao contrário do que muita gente acha, Elden Ring vai muito além de um "Dark Souls 4". O novo game da FromSoftware traz muitas novidades para o gênero, a começar por ser uma aventura de "mundo aberto". Além disso, há vários elementos inéditos de jogabilidade e muito o que se fazer. Isso pode deixar jogadores novatos perdidos. Ter um bom começo, portanto, é fundamental. Confira um guia rápido com cinco conselhos que podem fazer a diferença nas Terras Intermédias.</p>
        <h2>►A classe faz diferença</h2>
        <p>Ainda que, ao longo do jogo, você possa redistribuir os pontos de atributos como bem desejar, a escolha da classe inicial é muito importante. Isso porque algumas começam com reforço de pontos em determinados atributos e trazem itens específicos. Há dez arquétipos selecionáveis. É bom ter em mente que alguns deles são mais úteis para jogadores iniciantes, enquanto outros demandam uma boa dose de experiência em games do tipo. O samurai, por exemplo, pode ser tentador, mas ele carrega um escudo que não absorve 100% do dano físico. Você vai ter que ser muito preciso na hora de aparar ataques. Leve em consideração também o seu estilo de jogo. Se você curte um combate mais próximo, não adianta escolher um mago ou personagens que depende de ataques de longa distância, por exemplo</p>
        <h2>►Seja curioso e explorador</h2>
        <p>Como diria Tolkien, autor de O Senhor dos Anéis, "nem todos que vagueiam estão perdidos". O mapa de Elden Ring é vasto, repleto de itens, cavernas e masmorras escondidas. Vale a pena montar no seu cavalo e sair sem rumo. O lado bom é que há uma profusão de locais de graça, que servem para o personagem recuperar a energia, encher seus frascos e realizar viagens rápidas. É possível enxergar esses locais à distância, especialmente à noite, então uma prioridade é ativar o máximo possível deles. (Ah, e por falar em períodos diferentes do dia, há inimigos que só aparecem em horários específicos.) Mesmo dentro de estruturas, como fortalezas e castelos, há diversos caminhos a se seguir. Alguns trazem recompensas bem interessantes. Elden Ring, definitivamente, não é para preguiçosos.</p>
        <h2>►Não banque o herói</h2>
        <p>Frequentemente, você terá que lidar com grupos grandes de inimigos. E, nessa situação, Elden Ring segue a cartilha de outros jogos da série Souls: correr de peito aberto contra vários adversários ao mesmo tempo quase sempre termina em morte. Além disso, quase nunca há a necessidade de matar todos os inimigos que você encontra pela frente. O jogo recompensa bastante a furtividade, então vale a pena usar essa estratégia. Ande agachado, trace rotas pelas quais você encontre menos inimigos e, se o combate for inevitável, tente matar o máximo possível de forma furtiva antes de começar a treta com todo mundo. E, claro, se isso ocorrer em uma parte aberta do mapa e as coisas ficarem feia, não pense duas vezes. Chame seu cavalo e dê no pé. O que nos leva ao próximo conselho.. </p>
        <h2>►Deixe o orgulho de lado</h2>
        <p>Tornar-se o Lorde Prístino é uma missão um tanto solitária. Mas isso não quer dizer que você tenha que andar sozinho o tempo todo. O modo online do game permite invocar outros jogadores - uma saída válida na hora de encarar um chefão ou um inimigo mais casca-grossa. O mesmo vale também para NPCs, que muitas vezes podem ser recrutados antes de confrontos mais difíceis. Ainda que eles não representem uma ajuda determinante na hora de causar dano, ao menos são capazes de desviar a atenção do inimigo, permitindo que você se cure. Resumindo: se quiser ter uma experiência mais agradável, saiba pedir ajuda.</p>
        <h2>►Use a criatividade e não desista</h2>
        <p>Elden Ring é aquele tipo de jogo que, frequentemente, coloca "bloqueios" para sua progressão. Geralmente, trechos de dificuldade mais elevada ou algum chefão mais poderoso. Não existe uma única forma de abordar essas situações. O lance é usar a criatividade. Tente matar inimigos de longe, explorar as arenas das batalhas contra os chefes, usar armas específicas, etc. Há momentos que são realmente complicados. Aí, não tem jeito: o melhor a fazer é simplesmente persistir. Por ser um game de mundo aberto, você sempre pode ir para outro canto do mapa, explorar a área, coletar itens para fortalecer armas e runas para ganhar níveis. Ficar mais poderoso quase sempre é uma saída para passpassar menos sufoco em Elden Ring.</p>
      </Content>
    </Container>

  )
}